# Generated by Django 5.2.7 on 2025-10-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_movie_age_limit_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
