# Generated by Django 5.2.7 on 2025-10-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_alter_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
