# Generated by Django 5.2.6 on 2025-12-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_food_foodorder_foodorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorderitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foodorderitem',
            name='food_order',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.PositiveIntegerField(default=0, help_text='Gioi han do tuoi xem phim'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(help_text='Thoi luong (phut)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_level',
            field=models.CharField(choices=[('SILVER', 'Bac'), ('GOLD', 'Vang'), ('DIAMOND', 'Kim Cuong')], default='SILVER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodOrder',
        ),
        migrations.DeleteModel(
            name='FoodOrderItem',
        ),
    ]
